name: ci
on: [push, workflow_dispatch]

jobs:
  ci:
    name: CI on amd64/archlinux:base
    runs-on: ubuntu-22.04
    container: amd64/archlinux:base
    steps:
      - uses: actions/checkout@v4
      - run: |
          pacman -Syu --needed --noconfirm python-pipx python-wxpython
          pipx install --global hatch
        name: Install dependencies
      - run: hatch fmt --check
        name: Lint
      - run: hatch -vv env create dev
        name: Create editable installation
      - run: hatch build
        name: Package into tarball and wheel
