name: ci
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04
    container: amd64/archlinux:base
    steps:
      - uses: actions/checkout@v4
      - run: |
          pacman -Syu --needed --noconfirm python-pipx python-pyqt5 python-pyqt6 python-wxpython
          pipx install --global hatch
        name: Install dependencies
      - run: hatch fmt --check
        name: Lint
      - run: hatch -vv env create dev
        name: Create editable installation
      - run: hatch build
        name: Package into tarball and wheel

  test:
    strategy:
      matrix:
        runs-on: ['macos-13', 'macos-14', 'ubuntu-24.04', 'windows-2022']
        python-version: ['3.10', '3.11', '3.12', '3.13', 'pypy3.10']
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: python -m pip install pytest .
        name: Install testing requirements
      - run: python -m pytest
        name: Test
